core/urls.py
from django.urls import path

from .views import *

app_name = 'core'
urlpatterns = [
    path('', IndexView.as_view(), name='index')
    ]

event/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import *

app_name = 'event'
urlpatterns = [
    path('list/', EventListView.as_view(), name='list'),
    path('user/<slug>/list/', UserEventListView.as_view(), name='user-list'),
    path('country/<slug>/list/', CountryEventListView.as_view(), name='country-list'),
    path('create/', EventCreateView.as_view(), name='create'),
    path('<int:pk>/edit/', login_required(EventUpdateView.as_view()), name='edit'),
    path('<int:pk>/', EventDetailView.as_view(), name='detail'),
    path('<int:pk>/publish/', login_required(EventPublishView.as_view()), name='publish'),
    path('<int:pk>/unpublish/', login_required(EventUnpublishView.as_view()), name='unpublish'),
    path('<int:pk>/join/', login_required(UserJoinView.as_view()), name='user-join'),
    path('<int:pk>/unjoin/', login_required(UserUnjoinView.as_view()), name='user-unjoin'),
]

opentalks/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from opentalks import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('event/', include('event.urls', namespace='event')),
    path('froala_editor/', include('froala_editor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    instagram = models.CharField(max_length=100, blank=True)
    facebook = models.CharField(max_length=100, blank=True)
    about = models.CharField(max_length=1000, blank=True)


# Create your models here.
class Country(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название страны(на английском)')
    slug = models.SlugField()
    is_active = models.BooleanField(default=True, verbose_name='Открыта для выбора?')
    is_worldwide = models.BooleanField(default=False, verbose_name='Для всего мира?')

    def __str__(self):
        return self.title

event/models.py
# from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse
from core.models import Country, User


class Event(models.Model):
    user = models.ForeignKey(User, verbose_name='Создатель', related_name='events', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Название события')
    short_description = models.CharField(max_length=1000, verbose_name='Краткое описание', blank=True)
    full_description = models.TextField(verbose_name='Полное описание')
    start_at = models.DateTimeField(verbose_name='Дата начала')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    url = models.URLField(verbose_name='Ссылка на мероприятие')
    url_id = models.CharField(max_length=255, verbose_name='ID мероприятия', blank=True)
    url_password = models.CharField(max_length=255, verbose_name='Пароль мероприятия', blank=True)
    max_people = models.PositiveSmallIntegerField(default=10, verbose_name='Максимальное кол-во участников')
    country = models.ForeignKey(Country, related_name='country_events', verbose_name='Страна', on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True, verbose_name='Активно?')
    views = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')

    def get_absolute_url(self):
        return reverse('event:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-views', 'start_at')


class EventParticipant(models.Model):
    event = models.ForeignKey(Event, verbose_name='Событие', related_name='participants', on_delete=models.NOT_PROVIDED)
    user = models.ForeignKey(User, verbose_name='Участник', related_name='in_events', on_delete=models.NOT_PROVIDED)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('event:detail', kwargs={'pk': self.event.pk})

event/forms.py
from django import forms

from event.models import Event


class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ['title', 'start_at', 'short_description', 'full_description', 'country', 'url', 'url_id',
                  'url_password']

event/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from event.forms import EventForm
from .models import *


class EventListView(ListView):
    model = Event
    queryset = Event.objects.filter(is_active=True)


class UserEventListView(ListView):
    model = Event
    slug_field = 'user'

    def get_queryset(self):
        self.user = get_object_or_404(User, username=self.kwargs['slug'])
        if self.user == self.request.user:
            return Event.objects.filter(user=self.user)
        else:
            return Event.objects.filter(user=self.user, is_active=True)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the website
        context['specific_user'] = self.user

        return context


class CountryEventListView(ListView):
    model = Event
    slug_field = 'country'

    def get_queryset(self):
        country = get_object_or_404(Country, slug=self.kwargs['slug'])
        return Event.objects.filter(country=country, is_active=True)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        country = get_object_or_404(Country, slug=self.kwargs['slug'])
        # Add in the website
        context['specific_country'] = country
        context['country_list'] = Country.objects.filter(is_active=True).exclude(id=country.id)

        return context


class EventCreateView(CreateView):
    model = Event
    template_name = 'event/event_form.html'
    form_class = EventForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['country_list'] = Country.objects.filter(is_active=True)
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(EventCreateView, self).form_valid(form)


class EventDetailView(DetailView):
    model = Event

    def dispatch(self, request, *args, **kwargs):
        """ Добавляем просмотры """
        obj = self.get_object()
        obj.views = obj.views + 1
        obj.save()
        return super(EventDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        event = self.get_object()
        context['joined_users'] = EventParticipant.objects.filter(event=event)
        if self.request.user.is_authenticated:
            context['event_participant'] = EventParticipant.objects.filter(user=self.request.user,
                                                                           event=event).exists()

        return context


class EventUpdateView(UpdateView):
    model = Event
    form_class = EventForm

    def dispatch(self, request, *args, **kwargs):
        """ Making sure that only owners can unpublish bugs """
        obj = self.get_object()
        if obj.user != self.request.user:
            return redirect(obj)
        return super(EventUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['country_list'] = Country.objects.filter(is_active=True)
        return context


class EventPublishView(UpdateView):
    model = Event
    fields = []

    def dispatch(self, request, *args, **kwargs):
        """ Making sure that only owners can publish bugs """
        obj = self.get_object()
        if obj.user != self.request.user:
            return redirect(obj)
        return super(EventPublishView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = True
        # self.object.published_at = timezone.now()
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class EventUnpublishView(UpdateView):
    model = Event
    fields = []

    def dispatch(self, request, *args, **kwargs):
        """ Making sure that only owners can unpublish bugs """
        obj = self.get_object()
        if obj.user != self.request.user:
            return redirect(obj)
        return super(EventUnpublishView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class UserJoinView(UpdateView):
    model = Event
    fields = []

    def form_valid(self, form):
        ep = EventParticipant.objects.create(event=self.object, user=self.request.user)
        ep.save()

        return super(UserJoinView, self).form_valid(form)


class UserUnjoinView(UpdateView):
    model = Event
    fields = []

    def form_valid(self, form):
        ep = get_object_or_404(EventParticipant, event=self.kwargs['pk'], user=self.request.user)
        ep.delete()

        return super(UserUnjoinView, self).form_valid(form)

templates/event/event_detail.html
{% extends 'main.html' %}
{% load static %}

{% block page_css %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" type="text/css"
          media="all" rel="stylesheet"/>
    <link href="{% static 'froala_editor/css/froala_editor.min.css' %}" type="text/css" media="all" rel="stylesheet"/>
    <link href="{% static 'froala_editor/css/froala_style.min.css' %}" type="text/css" media="all" rel="stylesheet"/>
    <link href="{% static 'froala_editor/css/plugins/image.min.css' %}" type="text/css" media="all" rel="stylesheet"/>
    <link href="{% static 'core/css/lightgallery.css' %}" type="text/css" media="all" rel="stylesheet"/>
{% endblock %}

{% block content %}
    <div class="container ">
        <div class="row">
            <div class="col-md-8 col-12 pt-4">
                {{ form.error }}
                {{ form.errors }}

                <h4>{{ object.title }}</h4>
                <div class="row">
                    <div class="col-3">
                        Status:
                    </div>
                    <div class="col-9">
                        {% if object.is_active %}
                            <span class="text-success">published</span>
                        {% else %}
                            <span class="text-warning">unpublished</span>
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        Created by:
                    </div>
                    <div class="col-9">
                        <a target="_blank" href="{% url 'event:user-list' object.user %}">{{ object.user }}</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        When:
                    </div>
                    <div class="col-9">
                        {{ object.start_at|date:'Y-m-d H:i' }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        Country:
                    </div>
                    <div class="col-9">
                        {{ object.country }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        URL:
                    </div>
                    <div class="col-9">
                        {% if user.is_authenticated %}
                            <a target="_blank" href="{{ object.url }}">{{ object.url }}</a>
                        {% else %}
                            <p>Only registered users can view info. <a href="{% url 'account_signup' %}">Sign Up</a></p>
                        {% endif %}
                    </div>
                </div>
                {% if object.url_id %}
                    <div class="row">
                        <div class="col-3">
                            Event ID:
                        </div>
                        <div class="col-9">
                            {% if user.is_authenticated %}
                                {{ object.url_id }}
                            {% else %}
                                <p>Only registered users can view info. <a href="{% url 'account_signup' %}">Sign Up</a>
                                </p>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
                {% if object.url_password %}
                    <div class="row">
                        <div class="col-3">
                            Event Password:
                        </div>
                        <div class="col-9">
                            {{ object.url_password }}
                        </div>
                    </div>
                {% endif %}
                <div id="short_description" class="row pt-4">
                    <div class="col-12">
                        <h5>Short Description:</h5>
                        {{ object.short_description|linebreaksbr }}
                    </div>
                </div>
                <div id="full_description" class="row pt-4">
                    <div class="col-12">
                        <h5>Full Description:</h5>
                        {{ object.full_description|safe }}
                    </div>
                </div>
                {% if object.user == request.user %}
                    <a href="{% url 'event:edit' object.id %}" class="btn btn-outline-primary mt-4">Edit</a>
                    {% if object.is_active %}
                        <form action="{% url 'event:unpublish' object.id %}" method="post" class="pt-2">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-warning">Unpublish</button>
                        </form>
                    {% else %}
                        <form action="{% url 'event:publish' object.id %}" method="post" class="pt-2">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-success">Publish</button>
                        </form>
                    {% endif %}
                {% endif %}
                {% if not event_participant and user.is_authenticated %}
                    <form action="{% url 'event:user-join' event.pk %}" method="post" class="pt-2">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-info">Join <i class="fa fa-thumbs-up"></i></button>
                    </form>
                {% elif event_participant and user.is_authenticated %}
                    <form action="{% url 'event:user-unjoin' event.pk %}" method="post" class="pt-2">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-info">Unjoin <i class="fa fa-thumbs-down"></i>
                        </button>
                    </form>
                {% endif %}
            </div>
            <div class="col-md-4 col-12 pt-4">
                <h4>Joined users</h4>
                <div class="list-group">
                    {% for ju in joined_users %}
                        <a href="#"
                           class="list-group-item list-group-item-action {% if ju.user == user %}list-group-item-primary{% endif %}">@{{ ju.user }}</a>
                    {% empty %}
                        <p>Noone joined yet ((</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_js %}
    <script type="text/javascript" src="{% static 'core/js/lightgallery.min.js' %}"></script>
    <script>
        $('.fr-fic').on('click', function () {
            elements = [];
            $('#details').find('img').each(function () {
                elements.push({
                    "src": $(this).attr('src'),
                    'thumb': $(this).attr('src')
                })
            });
            {#            console.log(elements);#}

            $(this).lightGallery({
                dynamic: true,
                dynamicEl: elements
            })
        });
    </script>
{% endblock %}

templates/event/event_form.html
{% extends 'main.html' %}
{% load static %}

{% block page_css %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" type="text/css"
          media="all" rel="stylesheet"/>
    <link href="{% static 'froala_editor/css/froala_editor.min.css' %}" type="text/css" media="all" rel="stylesheet"/>
    <link href="{% static 'froala_editor/css/froala_style.min.css' %}" type="text/css" media="all" rel="stylesheet"/>
    <link href="{% static 'froala_editor/css/plugins/image.min.css' %}" type="text/css" media="all" rel="stylesheet"/>
    <link href="{% static 'froala_editor/css/plugins/video.min.css' %}" type="text/css" media="all" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">

{#    <link rel="stylesheet" href="{% static 'core/css/bootstrap-datetimepicker.min.css' %}"/>#}
    <link rel="stylesheet" href="{% static 'core/css/jquery.datetimepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container pt-4">
        <div class="row">
            <div class="col-12">
                {{ form.error }}
                {{ form.errors }}
                <form action="" method="post">
                    {% csrf_token %}
                    {#                    <div class="form-group row">#}
                    {#                        <label for="exampleInputEmail1" class="col-sm-2 col-form-label">Url</label>#}
                    {#                        <div class="col-sm-10">#}
                    {#                            <input type="url" class="form-control" id="id_url" name="url"#}
                    {#                                   aria-describedby="emailHelp"#}
                    {#                                   placeholder="https://google.com/page/with/bug">#}
                    {#                            <small id="emailHelp" class="form-text text-muted">where the bug was found</small>#}
                    {#                        </div>#}
                    {#                    </div>#}
                    <div class="form-group row">
                        <label for="id_title" class="col-sm-2 col-form-label">Title</label>
                        <div class="col-sm-10">
                            <input type="text" id="id_title" name="title" class="form-control" required
                                   placeholder="Please, explain it well in few words. It is very important." value="{{ object.title }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_start_at" class="col-sm-2 col-form-label">Start Date/Time</label>
                        <div class="col-sm-10">
                            <input type="text" id="id_start_at" name="start_at" class="form-control" required
                                   placeholder="04.30.2020" autocomplete="off" value="{{ object.start_at|date:'Y-m-d H:i' }}">
                        </div>
                    </div>
                    <hr>
                    <div class="form-group row">
                        <label for="id_url" class="col-sm-2 col-form-label">Event URL</label>
                        <div class="col-sm-10">
                            <input type="text" id="id_url" name="url" class="form-control" required
                                   placeholder="Here can be link to the Zoom room or Clickmeeting and etc"
                                    value="{{ object.url }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_url_id" class="col-sm-2 col-form-label">Event ID</label>
                        <div class="col-sm-10">
                            <input type="text" id="id_url_id" name="url_id" class="form-control"
                                   placeholder="ID of the Event, if necessary" value="{{ object.url_id }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_url_id" class="col-sm-2 col-form-label">Event Password</label>
                        <div class="col-sm-10">
                            <input type="text" id="id_url_password" name="url_password" class="form-control"
                                   placeholder="Password of the Event, if necessary" value="{{ object.url_password }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_max_people" class="col-sm-2 col-form-label">Maximum participants</label>
                        <div class="col-sm-10">
                            <input type="text" id="id_max_people" name="max_people" class="form-control" value="{% if object.max_people %}{{ object.max_people }}{% else %}10{% endif %}"
                                   placeholder="">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_max_people" class="col-sm-2 col-form-label">Country</label>
                        <div class="col-sm-10">
                            <select id="id_max_people" name="country" class="form-control">
                                {% for country in country_list %}
                                    <option value="{{ country.id }}" {% if object.country == country %}selected="selected"{% endif %}>{{ country.title }}</option>
                                {% empty %}
                                    <option value="">There's no countries yet((</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group pt-4">
                        <label for="id_short_description">Short Description</label>
                        <textarea id="id_short_description" name="short_description" class="form-control"
                                  rows="3" placeholder="no more that 2 sentences" autocomplete="off">{{ object.short_description|linebreaksbr }}</textarea>
                    </div>
                    <div class="form-group pt-4">
                        <label for="id_full_description">Full Description</label>
                        <textarea id="id_full_description" name="full_description" class="form-control"
                                  rows="6" placeholder="Explain what you want to do)))" autocomplete="off">{{ object.full_description|linebreaksbr }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-outline-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_js %}
    <script type="text/javascript" src="{% static 'froala_editor/js/froala_editor.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'froala_editor/js/froala-django.js' %}"></script>
    <script type="text/javascript" src="{% static 'froala_editor/js/plugins/image.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'froala_editor/js/plugins/video.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'froala_editor/js/plugins/paragraph_format.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'froala_editor/js/plugins/fullscreen.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'froala_editor/js/plugins/link.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'froala_editor/js/plugins/quote.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'froala_editor/js/plugins/lists.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'froala_editor/js/plugins/align.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'froala_editor/js/plugins/code_view.min.js' %}"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>
{#    <script type="text/javascript" src="{% static 'core/js/bootstrap-datetimepicker.min.js' %}"></script>#}
    <script src="{% static 'core/js/jquery.datetimepicker.full.min.js' %}"></script>
    <script>
    $('#id_full_description').froalaEditor({
        "inlineMode": false,
        "toolbarButtons": ['bold', 'italic', 'insertLink', 'insertHR', 'clearFormatting', '|', 'paragraphFormat', 'quote', 'insertImage', 'insertVideo', '|', 'formatOL', 'formatUL', 'align', '|', 'undo', 'redo'],
        "imageUploadURL": "/froala_editor/image_upload/",
        "imageUploadParams": {"csrfmiddlewaretoken": "{{ csrf_token }}"},
        "fileUploadURL": "/froala_editor/file_upload/",
        "fileUploadParams": {"csrfmiddlewaretoken": "{{ csrf_token }}"},
        "videoAllowedProviders": ['youtube', 'vimeo'],
        "videoUpload": false,
        "height": 300
    });

    $('#id_start_at').datetimepicker({
      format: 'Y-m-d H:i',
        //format:'m.d.Y H:i',
      //lang:'en'
    });

    </script>
{% endblock %}

templates/event/event_list.html
{% extends 'main.html' %}
{% load static %}
{% load humanize %}


{% block content %}
    <div class="container ">
        <div class="row pt-4">
            <div class="col-md-8 col-12">
                <h4>List of Events
                    {% if specific_user %}
                        created by <span class="text-primary">@{{ specific_user.username }}</span>
                    {% endif %}
                    {% if specific_country %}
                        created in <span class="text-primary">{{ specific_country.title }}</span>
                    {% endif %}

                </h4>
                {#                {% if website %}#}
                {#                    <h4>List of bugs in the <a target="_blank" href="{{ website.domain }}">{{ website.domain }}</a></h4>#}
                {#                {% elif username %}#}
                {#                    <h4>List of bugs created by user <span class="text-primary">{{ username }}</span></h4>#}
                {#                {% else %}#}
                {#                    <h4>Top Bugs</h4>#}
                {#                {% endif %}#}

                <div class="list-group">
                    {% for event in object_list %}
                        {% include 'event/include/event_row.html' %}
                    {% empty %}
                        <p>No events yet.</p>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4 col-12">
            {% if specific_user %}
                <h4><span class="text-primary">@{{ specific_user }}</span> info</h4>
                <small>{{ specific_user.about }}dfgdfgs</small>
                <div class="list-group mt-1">
                  <a class="list-group-item list-group-item-action " id="list-home-list" href="#list-home">Instagram</a>
                  <a class="list-group-item list-group-item-action " id="list-home-list" href="#list-home">Facebook</a>
                </div>

                </div>
            {% elif specific_country %}
                <h4>Other countries</h4>
            {% endif %}
                <div class="list-group">
                    {% for country in country_list %}
                        <a href="{% url 'event:country-list' country.slug %}"
                           class="my-1 list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            {{ country.title }} <span class="badge badge-primary badge-pill">{{ country.country_events.count }}</span>
                        </a>
                    {% empty %}
                        <p>Nothing found :(</p>
                    {% endfor %}
                </div>
{#                <div class="list-group">#}
{#                    {% for site in sites_list %}#}
{#                        <a href="#}
{#                            {% if specific_user %}#}
{#                            {% url 'bug:specific-user-website-list' specific_user.id site.id %}#}
{#                            {% else %}#}
{#                            {% url 'bug:specific-website-list' site.id %}#}
{#                            {% endif %}#}
{#                                "#}
{#                           class="my-1 list-group-item list-group-item-action d-flex justify-content-between align-items-center">#}
{#                            <img src="http://{{ site.domain }}/favicon.ico" alt="" width="16"> {{ site.domain }}#}
{#                            <span class="badge badge-primary badge-pill">{{ site.get_active_bugs_count }}</span>#}
{#                        </a>#}
{#                    {% empty %}#}
{#                        <p>Nothing found :(</p>#}
{#                    {% endfor %}#}
{##}
{#                </div>#}
            </div>
        </div>
    </div>
{% endblock %}