core/urls.py
from django.urls import path

from .views import *

app_name = 'core'
urlpatterns = [
    path('', IndexView.as_view(), name='index')
    ]

event/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import *

app_name = 'event'
urlpatterns = [
    path('list/', EventListView.as_view(), name='list'),
    path('user/<slug>/list/', UserEventListView.as_view(), name='user-list'),
    path('country/<slug>/list/', CountryEventListView.as_view(), name='country-list'),
    path('create/', EventCreateView.as_view(), name='create'),
    path('<int:pk>/edit/', login_required(EventUpdateView.as_view()), name='edit'),
    path('<int:pk>/', EventDetailView.as_view(), name='detail'),
    path('<int:pk>/publish/', login_required(EventPublishView.as_view()), name='publish'),
    path('<int:pk>/unpublish/', login_required(EventUnpublishView.as_view()), name='unpublish'),
    path('<int:pk>/join/', login_required(UserJoinView.as_view()), name='user-join'),
    path('<int:pk>/unjoin/', login_required(UserUnjoinView.as_view()), name='user-unjoin'),
]

opentalks/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from opentalks import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('event/', include('event.urls', namespace='event')),
    path('froala_editor/', include('froala_editor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    instagram = models.CharField(max_length=100, blank=True)
    facebook = models.CharField(max_length=100, blank=True)
    about = models.CharField(max_length=1000, blank=True)


# Create your models here.
class Country(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название страны(на английском)')
    slug = models.SlugField()
    is_active = models.BooleanField(default=True, verbose_name='Открыта для выбора?')
    is_worldwide = models.BooleanField(default=False, verbose_name='Для всего мира?')

    def __str__(self):
        return self.title

templates/main.html
{% load static %}
{#{% load staticfiles %}#}
{% load humanize %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Now You Know What TODO :)">
    <meta name="author" content="Albert B @hardqode">

    <title>{% block page_title %}OpenTalks{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    {#    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">#}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link href="{% static 'core/css/main.css' %}" rel="stylesheet">

    <link rel="shortcut icon" href="{% static 'core/img/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'core/img/favicon.ico' %}" type="image/x-icon">

    {% block page_css %}
    {% endblock %}
</head>
<body>

{% block header %}
    <section class="container bg-white">
        <nav class="navbar navbar-expand-lg navbar-light bg-white px-0">
            <a class="navbar-brand" href="{% url 'core:index' %}">OpenTalks</a>
            <a class="btn btn-outline-primary btn d-sm-none ml-auto mr-2"
               href="{% url 'event:create' %}">Create</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'event:list' %}">Events</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item d-none d-md-inline my-auto mr-4">
                        <a class="btn btn-outline-primary btn-sm" href="{% url 'event:create' %}">Create</a>
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button"
                               data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="profileDropdown">
                                <a class="dropdown-item" href="{% url 'event:user-list' user.username %}">My Events</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'account_change_password' %}">Edit password</a>
                                <a class="dropdown-item" href="{% url 'account_email' %}">Edit email</a>
                                <div class="dropdown-divider"></div>
                                <a id="id_logout" class="dropdown-item" href="">Logout</a>
                                <form id="form_logout" method="post" action="{% url 'account_logout' %}">
                                    {% csrf_token %}
                                </form>
                            </div>
                        {% else %}
                            <a href="{% url 'account_login' %}" class="nav-link">Login</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>
    </section>
{% endblock %}
{% block content %}
    {% if user.is_anonymous %}
        <div class="jumbotron jumbotron-fluid mb-0">
            <div class="container ">
                <div class="row">
                    <div class="col-md-6 col-12">
                        <h1 class="display-5">Create, Join, Take Fun</h1>
                        <p class="lead">everyone is welcome</p>
                        <p class="lead">Join the world's largest relax community :))</p>
                    </div>
                    <div class="col-md-6 col-12">
                        {#                <div class="row">#}
                        {#                    <div class="col">#}
                        {#                        <button type="button" class="btn btn-block btn-primary">Facebook</button>#}
                        {#                    </div>#}
                        {#                    <div class="col">#}
                        {#                        <button type="button" class="btn btn-block btn-secondary">Google</button>#}
                        {#                    </div>#}
                        {#                </div>#}
                        {#                <p class="text-center">OR</p>#}
                        <form method="post" action="{% url 'account_signup' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text" style="width: 100px">Username</div>
                                    </div>
                                    <input type="text" name="username" class="form-control"
                                           placeholder="jblack0506">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text" style="width: 100px">Email</div>
                                    </div>
                                    <input type="email" name="email" class="form-control"
                                           placeholder="jblack@example.com">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text" style="width: 100px">Password</div>
                                    </div>
                                    <input type="password" name="password1" class="form-control"
                                           placeholder="********">
                                </div>
                            </div>
                            <div class="form-check">
                                <div class="row">
                                    <div class="col-3 mx-0 px-0">
                                        <button type="submit" class="btn btn btn-outline-secondary">Sign Up</button>
                                    </div>
                                    <div class="col-9"><input type="checkbox" class="form-check-input"
                                                              id="exampleCheck1"
                                                              disabled checked>
                                        <label class="form-check-label small" for="exampleCheck1">By registering, you
                                            agree
                                            to
                                            the
                                            privacy policy and terms of service.</label></div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="container ">
        <div class="row ">
            <div class="col-md-8 col-12 pt-4">
                <h4>Top Events</h4>
                <div class="list-group">
                    {% for event in events_list %}
                        {% include 'event/include/event_row.html' %}
                    {% empty %}
                        <p>No bugs yet.</p>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4 col-12 pt-4">
                <h4>Countries</h4>
                <div class="list-group">
                    {% for country in country_list %}
                        <a href="{% url 'event:country-list' country.slug %}"
                           class="my-1 list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            {{ country.title }} <span class="badge badge-primary badge-pill">{{ country.country_events.count }}</span>
                        </a>
                    {% empty %}
                        <p>Nothing found :(</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    <footer class="pt-4 mt-md-5 pt-md-5 border-top container">
        <div class="row">
            <div class="col-12 col-md-2 text-md-left text-center">
                <a href="" class="logo-link">
                    <h5 class="my-0 mr-md-auto font-weight-normal">OpenTalks</h5>
                </a>
                <small class="d-block mb-3 text-muted">© 2020 It Is CoronaTime</small>
            </div>
            <div class="col-md text-md-left text-center">
                <a class="p-2 text-dark" href="{% url 'event:list' %}">Events</a>
                {#                <span class="p-2 text-dark text-muted" href="#">Apps</span>#}
            </div>
            <div class="col-md text-md-right text-center">
                <span class="p-2 text-dark">created with 10ve by <a target="_blank" class=""
                                                                    href="https://fb.com/aiksu">Albert B</a></span>
                <small class="d-block mb-3 mr-2 text-muted">© HardQode</small>
            </div>
            {#        <div class="col-6 col-md">#}
            {#            <h5>Contributors</h5>#}
            {#            <ul class="list-unstyled text-small">#}
            {#                <li><a target="_blank" class="text-muted" href="https://fb.com/aiksu">Albert B.</a></li>#}
            {#                <li><a target="_blank" class="text-muted" href="https://fb.com/krasnovvi">Vitaliy K.</a></li>#}
            {#                <li><a target="_blank" class="text-muted" href="https://hardqode.com">HardQode™</a></li>#}
            {#            </ul>#}
            {#        </div>#}
        </div>
    </footer>
{% endblock %}

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{#<script src="https://code.jquery.com/jquery-3.4.1.min.js"#}
{#  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="#}
{#  crossorigin="anonymous"></script>#}
{#<script src="{% static 'core/js/jquery-3.4.1.min.js' %}"></script>#}
<script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>
<script type="text/javascript" src="{% static 'core/js/moment-with-locales.js' %}"></script>

{#<script src="{% static 'core/js/bootstrap.min.js' %}"></script>#}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script>
    function getCSRF() {
        return $('input[name="csrfmiddlewaretoken"]').val();
    }

    {#        $('#id_signup').on('submit', function () {#}
    {#            formdata = new FormData($(this));#}
    {#            $.ajax({#}
    {#                    type: 'POST',#}
    {#                    url: $(this).attr('action'),#}
    {#                    headers: {"X-CSRFToken": getCSRF()},#}
    {#                    processData: false,#}
    {#                    contentType: false,#}
    {#                    data: formdata,#}
    {#                    success: function (data, textStatus, xhr) {#}
    {#                        console.log(data)#}
    {#                    },#}
    {#                    error: function (data, textStatus, xhr) {#}
    {#                        console.log('error', data);#}
    {#                    }#}
    {#                }#}
    {#            );#}
    {#            return false;#}
    {#        });#}

    $('#id_logout').on('click', function () {
        $('#form_logout').submit();
        return false;
    })
</script>

{% block page_js %}

{% endblock %}
</body>
</html>